apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "liquibase-migrations.fullname" . }}-changelog
  labels:
    {{- include "liquibase-migrations.labels" . | nindent 4 }}
data:
  db.changelog-master.yaml: |-
    databaseChangeLog:
      - include:
          file: db/changelog/changes/001-initial-schema.yaml
      # Add more changelog files as needed