name: ASCII-Cowsay execution

on: push

jobs:
    cowsay_installation:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout Repo
            uses: actions/checkout@v4

          - name: Executing Shell script
            run: |
              sudo chmod +x shell.sh            
              ./shell.sh