name: first-workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repo
          uses: actions/checkout@v4

        - name: List & Read Files
          run: |
            echo "Welcome to GitHub Actions"
            ls -la
            cat Chart.yaml
        - name: Generate ASCII code
          run: |
            sudo apt-get install cowsay -y
            cowsay -f dummy-dragon "Run run, I'm a fluffy dragon" >> dummy-dragon.txt
            grep -i "dragon" dummy-dragon.txt
            cat dummy-dragon.txt
            ls
        # - name: Listing files
        #   run: ls -la
        # - name: Reading Chart.yaml
        #   run: cat Chart.yaml