name: first-workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repo
          uses: actions/checkout@v4
        - name: welcome message
          run: echo "Welcome to GitHub Actions"
        - name: Listing files
          run: ls -la
        - name: Reading Chart.yaml
          run: cat Chart.yaml