name: second-workflow-cowsay-installation

on: push

jobs:
  second_job: 
      runs-on: ubuntu-latest
      steps:
        - name: dummy second job
          run: |
            sudo apt-get install cowsay -y
            cowsay -f dragon "Run run, I'm a fluffy dragon" >> dummy-dragon.txt
            ls